repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      language_version: python3.7
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    - id: bandit
      language_version: python3.7